require "nvchad.mappings"

-- add yours here

local map = vim.keymap.set

map("n", ";", ":", { desc = "CMD enter command mode" })
map("i", "jk", "<ESC>")

map({ "n", "i", "v" }, "<C-s>", "<cmd>w<cr><esc>")

-- git
map("n", "<leader>gg", "<cmd>LazyGit<cr>", { desc = "LazyGit" })

map("n", "<leader>cn", "<cmd>Navbuddy<cr>", { desc = "Code Navigation" })

-- dap
-- stylua: ignore
map("n", "<leader>dB", function() require("dap").set_breakpoint(vim.fn.input "Breakpoint condition: ") end, { desc = "Breakpoint Condition" })
map("n", "<leader>db", function()
  require("dap").toggle_breakpoint()
end, { desc = "Toggle Breakpoint" })
map("n", "<leader>dc", function()
  require("dap").continue()
end, { desc = "Run/Continue" })
map("n", "<leader>dC", function()
  require("dap").run_to_cursor()
end, { desc = "Run to Cursor" })
map("n", "<leader>dg", function()
  require("dap").goto_()
end, { desc = "Go to Line (No Execute)" })
map("n", "<leader>di", function()
  require("dap").step_into()
end, { desc = "Step Into" })
map("n", "<leader>dj", function()
  require("dap").down()
end, { desc = "Down" })
map("n", "<leader>dk", function()
  require("dap").up()
end, { desc = "Up" })
map("n", "<leader>dl", function()
  require("dap").run_last()
end, { desc = "Run Last" })
map("n", "<leader>do", function()
  require("dap").step_out()
end, { desc = "Step Out" })
map("n", "<leader>dO", function()
  require("dap").step_over()
end, { desc = "Step Over" })
map("n", "<leader>dP", function()
  require("dap").pause()
end, { desc = "Pause" })
map("n", "<leader>dr", function()
  require("dap").repl.toggle()
end, { desc = "Toggle REPL" })
map("n", "<leader>ds", function()
  require("dap").session()
end, { desc = "Session" })
map("n", "<leader>dt", function()
  require("dap").terminate()
end, { desc = "Terminate" })
map("n", "<leader>dw", function()
  require("dap.ui.widgets").hover()
end, { desc = "Widgets" })

-- neotest
map("n", "<leader>+", "", { desc = "+test" })
map("n", "<leader>tt", function()
  require("neotest").run.run(vim.fn.expand "%s")
end, { desc = "Run File (Neotest)" })
map("n", "<leader>tT", function()
  require("neotest").run.run(vim.uv.cwd())
end, { desc = "Run All Test Files (Neotest)" })
map("n", "<leader>tr", function()
  require("neotest").run.run()
end, { desc = "Run Neearest (Neotest)" })
map("n", "<leader>tl", function()
  require("neotest").run.run_last()
end, { desc = "Run Last (Neotest)" })
map("n", "<leader>ts", function()
  require("neotest").summary.toggle()
end, { desc = "Toggle Summary (Neotest)" })
map("n", "<leader>to", function()
  require("neotest").output.open { enter = true, auto_close = true }
end, { desc = "Show Output (Neotest)" })
map("n", "<leader>tO", function()
  require("neotest").output_panel.toggle()
end, { desc = "Toggle Output Panel (Neotest)" })
map("n", "<leader>tS", function()
  require("neotest").run.stop()
end, { desc = "Stop (Neotest)" })
map("n", "<leader>tw", function()
  require("neotest").watch.toggle(vim.fn.expand "%s")
end, { desc = "Toggle Watch (Neotest)" })
map("n", "<leader>td", function()
  require("neotest").run.run { strategy = "dap" }
end, { desc = "Debug Nearest (Neotest)" })
